[package]
name = "autodemo"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
color-eyre = "0.6.3"
crossterm = "0.28.1"
serde_json = "1.0.140"
jsonschema = "0.29.0"
ratatui = "0.29.0"
serde = "1.0.218"
yaml-rust2 = "0.10.0"
serde_yaml2 = "0.1.2"
