# SPDX-FileCopyrightText: 2025 Albert Esteve <aesteve@redhat.com>
#
# SPDX-License-Identifier: GPL-3.0-or-later

stages:
  - name: "How to use Autopilot"
    actions:
      - type: "message"
        text: |
          Never make a typo again!
            Let autopilot type eveything for you
            or run programs
        style:
          color: "red"
          bold: true

      - type: "message"
        text: |
          Script complex demos without missing one argument
            or forgetting important steps
        style:
          color: "green"
          italic: true

      - type: "command"
        command: "echo 'Commands support hidden output'"
        hide_stdout: true
        hide_stderr: false
        style:
          color: "red"
          bold: true

      - type: "command"
        command: "head -4 README.md"

      - type: "message"
        text: "Run commands, as many times as you need, both locally and remotely"
        speed: 0
        style:
          color: "cyan"
          bold: true

      - type: "command"
        command: "echo 'Good Bye (two times)!'"
        loop:
          times: 2
          delay: 1000

  - name: "Working on a remote host"
    actions:
      - type: "message"
        text: "You can also run commands on remote hosts (with SSH)"

      - type: "command"
        command: "hostnamectl"
        remote:
          host: localhost
          port: 2222
          user: admin
          password: $env:REMOTE_PASSWORD
